variadic Options
Effect-TS/cli pull request #289
Opened 2023-03-30 22:43 UTC by tim-smart

2023-03-30 22:44 UTC, tim-smart commented on test/Options.ts
> +  it.effect("variadic - integers atMost 2", () =>
@IMax153 Not sure if we actually want to ignore extra options, or raise an error.

2023-03-30 23:34 UTC, IMax153 requested changes

2023-03-30 23:34 UTC, IMax153 commented on test/Options.ts
> +  it.effect("variadic - integers atMost 2", () =>
I think if we're specifying something like `atMost`, we should probably raise an error.

2023-03-31 00:19 UTC, tim-smart commented on src/internal_effect_untraced/options.ts
> +          } else if (acc.length > max) {
Ah, need to move this to prevent consuming more options than required.

2023-03-31 00:37 UTC, IMax153 approved these changes

2023-03-31 00:37 UTC, merged